name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Export
      run: yarn export
    - name: Lint
      run: yarn lint
    - name: Run tests
      run: yarn test:cov