[build]
  command = "npm run build && npm run export"
  publish = "out"
[build.environment]
  NODE_VERSION = "12.16.3"
[[redirects]]
  from = "/playlists/*"
  to = "/library"
  status = 200
  force = true